server:
  port: 9003
spring:
  application:
    name: shuhui-manager
  profiles:
    active: dev
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:cn/shuhui/**/mapping/*.xml
knife4j:
  enable: true
  setting:
    enableOpenApi: true
    enableSwaggerModels: true
    enableVersion: true
    enableFilterMultipartApis: false
  basic:
    enable: true
    username: admin
    password: admin

